language: java
sudo: required
dist: trusty
cache:
  directories: $HOME/.m2/
addons:
  apt:
    packages:
      - oracle-java8-installer
      - google-chrome-stable
      - chromium-browser
    sources:
      - google-chrome
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get install chromium-chromedriver
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/:/usr/lib/chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - mvn verify -B jacoco:report coveralls:report
